# Generated by Django 5.2.8 on 2026-04-04 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homestays', '0003_alter_facility_options_homestay_is_active_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='homestaybooking',
            name='payment_proof',
            field=models.ImageField(blank=True, null=True, upload_to='payment_proofs/'),
        ),
    ]
