# Generated by Django 5.2.8 on 2026-04-04 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homestays', '0004_homestaybooking_payment_proof'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homestay',
            name='facilities',
        ),
        migrations.DeleteModel(
            name='Facility',
        ),
        migrations.AddField(
            model_name='homestay',
            name='facilities',
            field=models.TextField(blank=True, default='[]'),
        ),
    ]
