# Generated by Django 6.0.3 on 2026-04-03 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_alter_product_id_alter_productcategory_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productorder',
            name='fulfillment_method',
            field=models.CharField(choices=[('pickup', 'Pengambilan di Toko Pusat Oleh-Oleh Desa'), ('delivery', 'Dikirim ke Alamat Pemesan')], default='pickup', max_length=20),
        ),
        migrations.AddField(
            model_name='productorder',
            name='payment_proof',
            field=models.ImageField(blank=True, null=True, upload_to='payment_proofs/'),
        ),
        migrations.AddField(
            model_name='productorder',
            name='shipping_cost',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='productorder',
            name='stock_deducted',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='productorder',
            name='address',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='productorder',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('ready_pickup', 'Ready for Pickup'), ('shipping', 'Shipping'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', max_length=20),
        ),
    ]
