# Generated by Django 5.2.8 on 2026-04-20 00:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('destinations', '0002_seed_destinations'),
    ]

    operations = [
        migrations.CreateModel(
            name='Guide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('category', models.CharField(choices=[('lokal', 'Lokal'), ('internasional', 'Internasional')], default='lokal', max_length=20)),
                ('languages', models.CharField(help_text='Pisahkan dengan koma, contoh: Indonesia, English, Japanese', max_length=255)),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to='guides/')),
                ('phone_number', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254)),
                ('bio', models.TextField(blank=True)),
                ('is_available', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='TourPackage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('description', models.TextField()),
                ('itinerary', models.TextField(blank=True, help_text='Agenda kegiatan wisata')),
                ('price_local', models.DecimalField(decimal_places=2, help_text='Harga untuk wisatawan lokal (IDR)', max_digits=12)),
                ('price_international', models.DecimalField(decimal_places=2, help_text='Harga untuk wisatawan mancanegara (IDR)', max_digits=12)),
                ('image_url', models.URLField(blank=True)),
                ('duration', models.CharField(help_text='Contoh: 4 Jam, Full Day', max_length=50)),
                ('max_participants', models.PositiveIntegerField(default=10)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('destination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tour_packages', to='destinations.destination')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PackageBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', models.CharField(max_length=30)),
                ('tourist_category', models.CharField(choices=[('lokal', 'Lokal'), ('mancanegara', 'Mancanegara')], default='lokal', max_length=20)),
                ('tour_date', models.DateField()),
                ('start_time', models.TimeField()),
                ('num_participants', models.PositiveIntegerField(default=1)),
                ('total_price', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=12)),
                ('payment_proof', models.ImageField(blank=True, null=True, upload_to='payment_proofs/')),
                ('notes', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('guide', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bookings', to='guide.guide')),
                ('tour_package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='guide.tourpackage')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
