# Generated by Django 5.2.8 on 2026-04-04 14:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DestinationCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(blank=True, unique=True)),
            ],
            options={
                'verbose_name': 'Destination Category',
                'verbose_name_plural': 'Destination Categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Destination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('location', models.CharField(max_length=255)),
                ('short_description', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('image_url', models.URLField(blank=True)),
                ('duration', models.CharField(blank=True, max_length=50)),
                ('difficulty', models.CharField(blank=True, max_length=50)),
                ('best_time', models.CharField(blank=True, max_length=100)),
                ('features', models.TextField(blank=True, help_text='Pisahkan dengan koma')),
                ('activities', models.TextField(blank=True, help_text='Pisahkan dengan koma')),
                ('is_eco_friendly', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='destinations', to='destinations.destinationcategory')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
